###
#Get and Initialize , please call first before doing anything else!!!
###
GET http://localhost:8080/coffees

###
POST http://localhost:8080/coffees
Content-Type: application/json

{
  "name": "Test1",
  "coffeeType": "coffee",
  "price": 7.7
}

###
DELETE http://localhost:8080/coffees
Content-Type: application/json

{
  "name": "melange",
  "coffeeType": "coffee",
  "price": 7.7
}

###
PUT http://localhost:8080/coffees
Content-Type: application/json

{
  "name": "melange",
  "coffeeType": "coffee",
  "price": 7.7
}